server:
  port: 9797

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  profiles:
    active: dev

jwt:
  secretKey: ${JWT_SECRET:default-secret-key}
  expiration: 86400000